/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-03-18 03:32:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.filebbs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.yong.filebbs.*;

public final class fileBbs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1742046395049L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1742267332119L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.yong.filebbs");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      com.yong.filebbs.FileBbsDAO filedao = null;
      filedao = (com.yong.filebbs.FileBbsDAO) _jspx_page_context.getAttribute("filedao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (filedao == null){
        filedao = new com.yong.filebbs.FileBbsDAO();
        _jspx_page_context.setAttribute("filedao", filedao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 250317 3. 파일 올린 것 조회-->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/myweb/css/mainLayout.css\"> <!-- / 슬러쉬부터 시작하면 절대경로 -->\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("h2{\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("table{\r\n");
      out.write("	width:550px;\r\n");
      out.write("	margin:0px auto;\r\n");
      out.write("}\r\n");
      out.write("table th{\r\n");
      out.write("	background-color:skyblue;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!--  상단 !!! -->\r\n");
      out.write("\r\n");
      out.write("<script> \r\n");
      out.write("// ' / ' 쓰면 절대겨경로가 되는데 절대경로 써야됨(?)\r\n");
      out.write("// 이렇게 써야 어느 위치에든 열 수 있음\r\n");
      out.write("function openLogin(){\r\n");
      out.write("	window.open('/myweb/member/login.jsp','login','width=550,height=350');\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write(" ");

 //로그인 창 250314
 String sname=(String)session.getAttribute("sname"); //object파일로 저장되므로 다운캐스팅 해줘야 사용 가능함
 
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <header> <!-- ui 변하지 않지만 컴퓨터가 상단으로 인식함 -->\r\n");
      out.write("      ");

      if(sname==null){
    	  
      out.write("\r\n");
      out.write("    	   <div><a href=\"javascript:openLogin()\">로그인</a>\r\n");
      out.write("    	   <a href=\"/myweb/member/memberJoin.jsp\">회원가입</a></div>\r\n");
      out.write("    	   ");

      }else {
    	  
      out.write("\r\n");
      out.write("    	<div> ");
      out.print(sname);
      out.write("님 로그인중..... | <a href=\"/myweb/member/logout.jsp\">로그아웃</a></div>\r\n");
      out.write("    		");

      }
      
      out.write("\r\n");
      out.write("      <!-- javascipt 쓸 수 있음openLogin함수 열도록 함 -->\r\n");
      out.write("     \r\n");
      out.write("      <h1>JSP Study Site</h1>\r\n");
      out.write("      <nav><!-- nav 시각적인 의미는 없지만  컴퓨터는 메뉴영역으로 인식함 -->\r\n");
      out.write("         <ul>\r\n");
      out.write("            <li><a href=\"/myweb\">Home</a></li><!-- 메뉴는 보통 링크로 감싸줘서 클릭대상자로 설정 -->\r\n");
      out.write("            <li><a href=\"#\">Profile</a></li>\r\n");
      out.write("            <li><a href=\"#\">자유게시판</a></li>\r\n");
      out.write("            <li><a href=\"/myweb/webfolder/webfolder.jsp\">Yong드라이브</a></li> <!-- 웹폴더라는 전제로 절대경로 -->\r\n");
      out.write("            <li><a href=\"#\">방명록</a></li>\r\n");
      out.write("         </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("   </header>");
      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("	<article>\r\n");
      out.write("		<h2>심플자료실</h2>\r\n");
      out.write("		<fieldset>\r\n");
      out.write("			<legend>자료목록</legend>\r\n");
      out.write("			<div>\r\n");
      out.write("				<input type=\"button\" value=\"파일 업로드\" onclick=\"location.href='fileBbsUploadForm.jsp;'\"> \r\n");
      out.write("			</div>\r\n");
      out.write("			<table>\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>번호</th>\r\n");
      out.write("						<th>파일명</th>\r\n");
      out.write("						<th>작성자</th>\r\n");
      out.write("					</tr> \r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody><!-- 여기서부턴 DB에서 가져온 정보로 할 거이므로 스크립트 열어줌 -->\r\n");
      out.write("				");

				ArrayList<FileBbsDTO> arr=filedao.fileBbsList();
				if(arr==null || arr.size()==0){
					
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"3\" align=\"center\">\r\n");
      out.write("						등록된 파일이 없습니다\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					");

				}else{
					for(int i=0; i<arr.size(); i++){
						// 사용자 입장에서는 MYWEB이 최상위 이 MYWEB으로 부터 파일BBS폴더에 업로드 폴더까지 접근해서 함
						//상대경로하면 files폴더에서 파일명
				
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>");
      out.print(arr.get(i).getIdx() );
      out.write("</td>\r\n");
      out.write("					<td><a href=\"files/");
      out.print(arr.get(i).getFilename());
      out.write("\">\r\n");
      out.write("					");
      out.print(arr.get(i).getFilename() );
      out.write("</a></td>\r\n");
      out.write("					<td>");
      out.print(arr.get(i).getWriter() );
      out.write("</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				");

			}
		}
				
      out.write("\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("		</fieldset>\r\n");
      out.write("	</article>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <footer><!-- 하단 영역 -->\r\n");
      out.write("   <hr>\r\n");
      out.write("      <div>Copyright &copy; Ssang Young cop. All rights reserved.</div>\r\n");
      out.write("   </footer>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
